sudo: required
services:
  - docker

before_install:
  - docker build -t romykusuma/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run romykusuma/react-test yarn test --coverage

after_success:
  - docker build -t romykusuma/multi-client ./client
  - docker build -t romykusuma/multi-nginx ./nginx
  - docker build -t romykusuma/multi-server ./server
  - docker build -t romykusuma/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push romykusuma/multi-client
  - docker push romykusuma/multi-nginx
  - docker push romykusuma/multi-server
  - docker push romykusuma/multi-worker
